;(function(){var dfltPluginCfg={"info":true};var dfltGlobalCfg={"site":583898,"log":"logc187","logSSL":"logs1187","domain":"xiti.com","secure":true,"pixelPath":"/hit.xiti","disableCookie":false,"cookieSecure":false,"cookieDomain":"","preview":false,"plgs":["RichMedia"],"lazyLoadingPath":"","documentLevel":"document","redirect":false,"activateCallbacks":true,"medium":"","ignoreEmptyChapterValue":false,"base64Storage":false};(function(a,b){a.ATInternet=a.ATInternet||{};a.ATInternet.Tracker=a.ATInternet.Tracker||{};a.ATInternet.Tracker.Plugins=a.ATInternet.Tracker.Plugins||{}})(window);
window.ATInternet.Utils=new function(){function a(b){var l=typeof b;if("object"!==l||null===b)return"string"===l&&(b='"'+b+'"'),String(b);var h,g,c=[],e=b&&b.constructor===Array;for(h in b)b.hasOwnProperty(h)&&(g=b[h],l=typeof g,"function"!==l&&"undefined"!==l&&("string"===l?g='"'+g.replace(/[^\\]"/g,'\\"')+'"':"object"===l&&null!==g&&(g=a(g)),c.push((e?"":'"'+h+'":')+String(g))));return(e?"[":"{")+String(c)+(e?"]":"}")}var b=this;b.cloneSimpleObject=function l(a,b){if("object"!==typeof a||null===
a||a instanceof Date)return a;var c=new a.constructor||a.constructor(),e;for(e in a)a.hasOwnProperty(e)&&(void 0===e||b&&void 0===a[e]||(c[e]=l(a[e])));return c};b.jsonSerialize=function(l){return"undefined"!==typeof JSON&&JSON.stringify?JSON.stringify(l):a(l)};b.jsonParse=function(a){try{if("undefined"!==typeof JSON&&JSON.parse)return JSON.parse(a);var b;b=null===a?a:"string"===typeof a?(new Function("return "+a))():!1;return b}catch(g){return null}};b.arrayIndexOf=function(a,b){return Array.indexOf?
a.indexOf(b):function(a){if(null==this)throw new TypeError;var c=Object(this),e=c.length>>>0;if(0===e)return-1;var d=0;1<arguments.length&&(d=Number(arguments[1]),d!=d?d=0:0!=d&&Infinity!=d&&-Infinity!=d&&(d=(0<d||-1)*Math.floor(Math.abs(d))));if(d>=e)return-1;for(d=0<=d?d:Math.max(e-Math.abs(d),0);d<e;d++)if(d in c&&c[d]===a)return d;return-1}.apply(a,[b])};b.genGuid=function(a){var b=new Date,g=function(a){a-=100*Math.floor(a/100);return 10>a?"0"+a:a};return g(b.getHours())+""+g(b.getMinutes())+
""+g(b.getSeconds())+""+function(a){return Math.floor(Math.random()*Math.pow(10,a))}(a-6)};b.getObjectKeys=function(a){var b=[],g;for(g in a)a.hasOwnProperty(g)&&b.push(g);return b};b.completeFstLevelObj=function(a,b,g){if(a){if(b)for(var c in b)!b.hasOwnProperty(c)||a[c]&&!g||(a[c]=b[c])}else a=b;return a};b.isPreview=function(){return window.navigator&&"preview"===window.navigator.loadPurpose};b.isPrerender=function(a){var h,g=!1,c=["webkit","ms"];if("prerender"===document.visibilityState)h="visibilitychange";
else for(var e=0;e<c.length;e++)"prerender"===document[c[e]+"VisibilityState"]&&(h=c[e]+"visibilitychange");if("undefined"!==typeof h){var d=function(e){a(e);b.removeEvtListener(document,h,d)};b.addEvtListener(document,h,d);g=!0}return g};var k=b.addEvtListener=function(a,b,g){a.addEventListener?a.addEventListener(b,g,!1):a.attachEvent&&a.attachEvent("on"+b,g)};b.removeEvtListener=function(a,b,g){a.removeEventListener?a.removeEventListener(b,g,!1):a.detachEvent&&a.detachEvent("on"+b,g)};b.loadScript=
function(a,b){var g;b=b||function(){};g=document.createElement("script");g.type="text/javascript";g.src=a.url;g.async=!1;g.defer=!1;g.onload=g.onreadystatechange=function(a){a=a||window.event;if("load"===a.type||/loaded|complete/.test(g.readyState)&&(!document.documentMode||9>document.documentMode))g.onload=g.onreadystatechange=g.onerror=null,b(null,a)};g.onerror=function(a,c,l){g.onload=g.onreadystatechange=g.onerror=null;b({msg:"script not loaded",event:a})};var c=document.head||document.getElementsByTagName("head")[0];
c.insertBefore(g,c.lastChild)};b.hashcode=function(a){var b=0;if(0===a.length)return b;for(var g=0;g<a.length;g++)var c=a.charCodeAt(g),b=(b<<5)-b+c,b=b&b;return b};b.setLocation=function(a){var b=a.location;a=window[a.target]||window;b&&(a.location.href=b)};b.dispatchCallbackEvent=function(a){var b=document.createEvent("Event");b.initEvent("ATCallbackEvent",!0,!0);b.name=a;document.dispatchEvent(b)};b.addCallbackEvent=function(a){document.createEvent("Event").initEvent("ATCallbackEvent",!0,!0);k(document,
"ATCallbackEvent",a)}};
var BuildManager=function(a){var b=this,k=function(a,c,b){a="&"+a+"=";return{param:a,paramSize:a.length,str:c,strSize:c.length,truncate:b}},f=function(c,d){var b="",l=0,f=!0,r;for(r in c)if(c.hasOwnProperty(r)){var p=c[r];if(p){var f=!1,g=d-l;if(p.strSize+p.paramSize<g)b+=p.param+p.str,l+=p.strSize+p.paramSize,c[r]=void 0,f=!0;else{p.truncate?(b+=p.param+p.str.substr(0,g),c[r].str=p.str.substr(g,p.strSize-1),c[r].strSize=c[r].str.length):p.strSize+p.paramSize>d&&(a.emit("Tracker:Hit:Build:Error",{lvl:"ERROR",
msg:'Too long parameter "'+p.param+'"',details:{value:p.str}}),c[r].str=c[r].str.substr(0,d-p.paramSize-1),c[r].strSize=c[r].str.length);break}}else f=!0}return[b,f?null:c]},l=["ati","atc","pdtl","stc","dz"],h=function(c,b,g){var h=function(a){if(a==={})return"";var c=[],b;b={};var e=0,d=!1,g=void 0,r,n,h;for(h in a)if(a.hasOwnProperty(h)){var q=a[h].value;"function"===typeof q&&(q=q());q=q instanceof Array?q.join(a[h].options.separator||","):"object"===typeof q?window.ATInternet.Utils.jsonSerialize(q):
"undefined"===typeof q?"undefined":q.toString();a[h].options.encode&&(q=encodeURIComponent(q));var t=k(h,q,-1<window.ATInternet.Utils.arrayIndexOf(l,h)),e=e+(t.paramSize+t.strSize);if(a[h].options.last)1490<q.length&&q.substr(0,1490),r=h,n=t;else if(b[h]=t,1500<b[h].paramSize+b[h].strSize&&!b[h].truncate){d=!0;g=h;break}}r&&(b[r]=n);b=[b,e,d,g];a=b[0];if(b[2])b=b[3],a=a[b],a.str=a.str.substr(0,1450),a.strSize=1450,e={},e.mherr=k("mherr","1",!1),e[b]=a,c.push(f(e,1500)[0]);else if(b=f(a,1500),null===
b[1])c=b[0];else for(c.push(b[0]);null!==b[1];)b=f(a,1500),c.push(b[0]);return c},t="";a.buffer.presentInFilters(b,"hitType")||(b=a.buffer.addInFilters(b,"hitType",["page"]));b=a.buffer.addInFilters(b,"hitType",["all"]);var r;if(c){b=a.buffer.addInFilters(b,"permanent",!0);b=a.buffer.get(b,!0);for(r in c)c.hasOwnProperty(r)&&(b[r]={value:c[r],options:{}});t=h(b)}else for(r in b=a.buffer.get(b,!0),t=h(b),b)b.hasOwnProperty(r)&&!b[r].options.permanent&&a.buffer.del(r);g&&g(t)},g=function(c){var b=a.getConfig("secure"),
l="https:"===document.location.protocol,l=b||l?a.getConfig("logSSL"):a.getConfig("log"),g=a.getConfig("baseURL"),f=a.getConfig("domain"),r=a.getConfig("pixelPath"),p=a.getConfig("site");(g||l&&f&&r)&&p?c&&c(null,(g?g:(b?"https://":"//")+l+("."+f)+r)+("?s="+p)):c&&c({message:"Config error"})},c=function(a,c,b){g(function(l,g){l?b&&b(l):h(a,c,function(a){var c=[],e=window.ATInternet.Utils.genGuid(13);if(a instanceof Array)if(1===a.length)c.push(g+"&mh=1-2-"+e+a[0]);else for(var d=1;d<=a.length;d++)c.push(g+
"&mh="+d+"-"+a.length+"-"+e+a[d-1]);else c.push(g+a);b&&b(null,c)})})};b.send=function(e,d){c(e,d,function(c,e){if(c)a.emit("Tracker:Hit:Build:Error",{lvl:"ERROR",msg:c.message,details:{hits:e}});else for(var d=0;d<e.length;d++)b.sendUrl(e[d])})};b.sendUrl=function(c){var b=function(c,b){return function(){return function(e){a.emit(c,{lvl:-1===c.indexOf("Error")?"INFO":"ERROR",details:{hit:b,event:e}})}}()},l=new Image;l.onload=b("Tracker:Hit:Sent:Ok",c);l.onerror=b("Tracker:Hit:Sent:Error",c);l.src=
c}},TriggersManager=function(){function a(a,b,g){for(var c=[],e=0;e<a.length;e++)a[e].callback(b,g),a[e].singleUse||c.push(a[e]);return c}function b(a,f,g,c){var e=a.shift();if("*"===e)return f["*"]=f["*"]||[],f["*"].push({callback:g,singleUse:c}),f["*"].length-1;if(0===a.length)return b([e,"*"],f,g,c);f["*"]=f["*"]||[];f[e]=f[e]||{};return b(a,f[e],g,c)}function k(b,f,g,c){var e=f.shift();"*"!==e&&(0===f.length?k(b,[e,"*"],g,c):g[e]&&(g[e]["*"]=a(g[e]["*"],b,c),k(b,f,g[e],c)))}var f={};this.on=function(a,
h,g){g=g||!1;return b(a.split(":"),f,h,g)};this.emit=function(b,h){f["*"]&&(f["*"]=a(f["*"],b,h));k(b,b.split(":"),f,h)}},PluginsManager=function(a){var b={},k={},f=0,l={},h=0,g=this.load=function(e,d){"function"===typeof d?"undefined"===typeof a.getConfig.plgAllowed||0===a.getConfig.plgAllowed.length||-1<a.getConfig.plgAllowed.indexOf(e)?(b[e]=new d(a),k[e]&&b[e]&&(k[e]=!1,f--,b[e+"_ll"]&&c(e+"_ll"),0===f&&a.emit("Tracker:Plugin:Lazyload:File:Complete",{lvl:"INFO",msg:"LazyLoading triggers are finished"})),
a.emit("Tracker:Plugin:Load:"+e+":Ok",{lvl:"INFO"})):a.emit("Tracker:Plugin:Load:"+e+":Error",{lvl:"ERROR",msg:"Plugin not allowed",details:{}}):a.emit("Tracker:Plugin:Load:"+e+":Error",{lvl:"ERROR",msg:"not a function",details:{obj:d}});return a},c=this.unload=function(c){b[c]?(b[c]=void 0,a.emit("Tracker:Plugin:Unload:"+c+":Ok",{lvl:"INFO"})):a.emit("Tracker:Plugin:Unload:"+c+":Error",{lvl:"ERROR",msg:"not a known plugin"});return a},e=this.isLazyloading=function(a){return a?!0===k[a]:0!==f},d=
function(a){return q(a)?(n(a),!0):!1},n=function(c){k[c]=!0;f++;ATInternet.Utils.loadScript({url:a.getConfig("lazyLoadingPath")+c+".js"})},q=function(a){return!b[a]&&!e(a)&&(b[a+"_ll"]?!0:!1)},t=function(a){l[a]?l[a]++:l[a]=1;h++};this.isExecWaitingLazyloading=function(){return 0!==h};a.exec=this.exec=function(c,d,f,g){var k=null,s=function(a,c,e,d){c=c.split(".");b[a]&&b[a][c[0]]&&(k=1<c.length&&b[a][c[0]][c[1]]?b[a][c[0]][c[1]].apply(b[a],e):b[a][c[0]].apply(b[a],e));d&&d(k)},u=function(c,b,e,d){t(c);
a.onTrigger("Tracker:Plugin:Load:"+c+":Ok",function(){s(c,b,e,function(b){l[c]--;h--;0===h&&a.emit("Tracker:Plugin:Lazyload:Exec:Complete",{lvl:"INFO",msg:"All exec waiting for lazyloading are done"});d&&d(b)})},!0)};q(c)?(u(c,d,f,g),n(c)):e(c)?u(c,d,f,g):s(c,d,f,g)};this.waitForDependencies=function(c,e){var f=function(a){for(var c={mcount:0,plugins:{}},e=0;e<a.length;e++)b.hasOwnProperty(a[e])||(c.mcount++,c.plugins[a[e]]=!0);return c}(c);if(0===f.mcount)a.emit("Tracker:Plugin:Dependencies:Loaded",
{lvl:"INFO",details:{dependencies:c}}),e();else for(var g in f.plugins)f.plugins.hasOwnProperty(g)&&(a.emit("Tracker:Plugin:Dependencies:Error",{lvl:"WARNING",msg:"Missing plugin "+g}),a.onTrigger("Tracker:Plugin:Load:"+g,function(a,c){var b=a.split(":"),d=b[3];"Ok"===b[4]&&(f.plugins[d]=!1,f.mcount--,0===f.mcount&&e())},!0),d(g))};this.init=function(){for(var a in ATInternet.Tracker.pluginProtos)ATInternet.Tracker.pluginProtos.hasOwnProperty(a)&&g(a,ATInternet.Tracker.pluginProtos[a])}},CallbacksManager=
function(a){var b={};this.init=function(){if(a.getConfig("activateCallbacks")){var f=a.getConfig("callbacks");(function(){if("undefined"!==typeof f&&f.include instanceof Array)for(var a=0;a<f.include.length;a++)ATInternet.Callbacks&&ATInternet.Callbacks.hasOwnProperty(f.include[a])&&(b[f.include[a]]={"function":ATInternet.Callbacks[f.include[a]]},ATInternet.Tracker.callbackProtos[f.include[a]]||(ATInternet.Tracker.callbackProtos[f.include[a]]=b[f.include[a]]));else for(a in ATInternet.Callbacks)ATInternet.Callbacks.hasOwnProperty(a)&&
(b[a]={"function":ATInternet.Callbacks[a]},ATInternet.Tracker.callbackProtos[a]||(ATInternet.Tracker.callbackProtos[a]=b[a]));if("undefined"!==typeof f&&f.exclude instanceof Array)for(a=0;a<f.exclude.length;a++)b[f.exclude[a]]&&(b[f.exclude[a]]=void 0);for(var h in b)b.hasOwnProperty(h)&&b[h]&&k(h,b[h]["function"])})();ATInternet.Utils.addCallbackEvent(function(a){if(a.name){var b=!0;"undefined"!==typeof f&&(f.include instanceof Array&&-1===ATInternet.Utils.arrayIndexOf(f.include,a.name)&&(b=!1),
f.exclude instanceof Array&&-1!==ATInternet.Utils.arrayIndexOf(f.exclude,a.name)&&(b=!1));if(ATInternet.Callbacks&&ATInternet.Callbacks.hasOwnProperty(a.name)){var g={};g[a.name]={"function":ATInternet.Callbacks[a.name]};b&&k(a.name,g[a.name]["function"]);ATInternet.Tracker.callbackProtos[a.name]||(ATInternet.Tracker.callbackProtos[a.name]=g[a.name])}}})}};var k=this.load=function(b,l){"function"===typeof l?(new l(a),a.emit("Tracker:Callback:Load:"+b+":Ok",{lvl:"INFO",details:{obj:l}})):a.emit("Tracker:Callback:Load:"+
b+":Error",{lvl:"ERROR",msg:"not a function",details:{obj:l}});return a}},BufferManager=function(a){var b={};this.set=function(a,f,g){g=g||{};g.hitType=g.hitType||["page"];b[a]={value:f,options:g}};var k=function(a,b,f){return(a=window.ATInternet.Utils.cloneSimpleObject(a[b]))&&!f?a.value:a},f=function h(a,c){if(!(a&&c instanceof Array&&a instanceof Array))return[];if(0===a.length)return c;var e=a[0],d,f=[],k=window.ATInternet.Utils.cloneSimpleObject(a);k.shift();for(var t=0;t<c.length;t++)if("object"!==
typeof e[1])b[c[t]]&&b[c[t]].options[e[0]]===e[1]&&f.push(c[t]);else{d=e[1].length;for(var r=0;r<d;r++)if(b[c[t]]&&b[c[t]].options[e[0]]instanceof Array&&0<=window.ATInternet.Utils.arrayIndexOf(b[c[t]].options[e[0]],e[1][r])){f.push(c[t]);break}}return h(k,f)};this.get=function(a,g){var c={};if("string"===typeof a)c=k(b,a,g);else for(var e=f(a,window.ATInternet.Utils.getObjectKeys(b)),d=0;d<e.length;d++)c[e[d]]=k(b,e[d],g);return c};this.presentInFilters=function g(a,b){return a&&0!==a.length?a[0][0]===
b?!0:g(a.slice(1),b):!1};this.addInFilters=function c(a,b,f,k){if(!a||0===a.length)return k?[]:[[b,f]];var t=a[0][0],r=a[0][1];t===b&&(r instanceof Array&&!(-1<window.ATInternet.Utils.arrayIndexOf(r,f[0]))&&r.push(f[0]),k=!0);return[[t,r]].concat(c(a.slice(1),b,f,k))};this.del=function(a){b[a]=void 0};this.clear=function(){b={}}},Tag=function(a,b,k){b=b||{};var f=this;f.version="5.6.1";var l=window.ATInternet.Utils.cloneSimpleObject(b);f.triggers=new TriggersManager(f);f.emit=f.triggers.emit;f.onTrigger=
f.triggers.on;var h=window.ATInternet.Utils.cloneSimpleObject(dfltGlobalCfg)||{},g;for(g in a)a.hasOwnProperty(g)&&(h[g]=a[g]);f.getConfig=function(a){return h[a]};f.setConfig=function(a,b,d){void 0!==h[a]&&d||(f.emit("Tracker:Config:Set:"+a,{lvl:"INFO",details:{bef:h[a],aft:b}}),h[a]=b)};f.configPlugin=function(a,b,d){h[a]=h[a]||{};for(var g in b)b.hasOwnProperty(g)&&void 0===h[a][g]&&(h[a][g]=b[g]);d&&(d(h[a]),f.onTrigger("Tracker:Config:Set:"+a,function(a,b){d(b.details.aft)}));return h[a]};f.getContext=
function(a){return l[a]};f.setContext=function(a,b){f.emit("Tracker:Context:Set:"+a,{lvl:"INFO",details:{bef:l[a],aft:b}});l[a]=b};f.delContext=function(a,b){f.emit("Tracker:Context:Deleted:"+a+":"+b,{lvl:"INFO",details:{key1:a,key2:b}});if(a)l.hasOwnProperty(a)&&(b?l[a]&&l[a].hasOwnProperty(b)&&(l[a][b]=void 0):l[a]=void 0);else if(b)for(var d in l)l.hasOwnProperty(d)&&l[d]&&l[d].hasOwnProperty(b)&&(l[d][b]=void 0)};f.plugins=new PluginsManager(f);f.buffer=new BufferManager(f);f.setParam=f.buffer.set;
f.getParams=function(a){return f.buffer.get(a,!1)};f.getParam=f.buffer.get;f.delParam=f.buffer.del;f.builder=new BuildManager(f);f.sendHit=f.builder.send;f.sendUrl=f.builder.sendUrl;f.callbacks=new CallbacksManager(f);f.setParam("ts",function(){return(new Date).getTime()},{permanent:!0,hitType:["all"]});f.getConfig("disableCookie")&&f.setParam("idclient","xxxxxx-NO",{permanent:!0,hitType:["all"]});f.getConfig("medium")&&f.setParam("medium",f.getConfig("medium"),{permanent:!0,hitType:["all"]});f.plugins.init();
f.callbacks.init();ATInternet.Tracker.instances.push(f);f.emit("Tracker:Ready",{lvl:"INFO",msg:"Tracker initialized",details:{tracker:f,args:{config:a,context:b,callback:k}}});k&&k(f)};ATInternet.Tracker.Tag=Tag;ATInternet.Tracker.instances=[];ATInternet.Tracker.pluginProtos={};
ATInternet.Tracker.addPlugin=function(a,b){b=b||ATInternet.Tracker.Plugins[a];if(!ATInternet.Tracker.pluginProtos[a]){ATInternet.Tracker.pluginProtos[a]=b;for(var k=0;k<ATInternet.Tracker.instances.length;k++)ATInternet.Tracker.instances[k].plugins.load(a,b)}};ATInternet.Tracker.delPlugin=function(a){if(ATInternet.Tracker.pluginProtos[a]){ATInternet.Tracker.pluginProtos[a]=void 0;for(var b=0;b<ATInternet.Tracker.instances.length;b++)ATInternet.Tracker.instances[b].plugins.unload(a)}};
ATInternet.Tracker.callbackProtos={};
}).call(window);;(function(){var dfltPluginCfg={"info":true};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.RichMedia=function(a){var b=new function(){this._timeout={};this.setTimeout=function(b,e,d){this._timeout[b]=this._timeout[b]||{};this._timeout[b][e]=window.setTimeout(function(){a.richMedia.send({action:"refresh",playerId:b,mediaLabel:e})},1E3*d)};this.setTimeoutObject=function(b,e,d){this._timeout[b]=this._timeout[b]||{};if("undefined"===typeof this._timeout[b][e]){var f=[],h;for(h in d)d.hasOwnProperty(h)&&f.push({delay:g(h,0),refresh:g(d[h],5)});f.sort(function(a,
b){return a.delay<b.delay?-1:a.delay>b.delay?1:0});this._timeout[b][e]={arrObj:f}}d=this._timeout[b][e];if(0<d.arrObj.length&&(f=d.arrObj[0].delay,h=d.arrObj[0].refresh,"number"===typeof f&&"number"===typeof h&&0<h)){d[f]=d[f]||{};var k=void 0;"undefined"!==typeof d.arrObj[1]&&(k=d.arrObj[1].delay);var l=0;"undefined"===typeof k?l=1:"number"===typeof d[f].num?l=Math.max(d[f].num-1,0):"number"===typeof k&&(l=Math.floor(60*(k-f)/h));d[f].num=l;0<l?d[f].timeout=window.setTimeout(function(){a.richMedia.send({action:"refresh",
playerId:b,mediaLabel:e})},1E3*h):"undefined"!==typeof d[f].timeout&&(window.clearTimeout(d[f].timeout),d[f].timeout=void 0,d.arrObj.splice(0,1),window.setTimeout(function(){a.richMedia.send({action:"refresh",playerId:b,mediaLabel:e})},1E3*h));this._timeout[b][e]=d}};this.clearTimeout=function(a,b){this._timeout[a]=this._timeout[a]||{};if("object"===typeof this._timeout[a][b])for(var d in this._timeout[a][b]){if(this._timeout[a][b].hasOwnProperty(d)){var f=this._timeout[a][b][d].num;"undefined"!==
typeof f&&0<f&&(window.clearTimeout(this._timeout[a][b][d].timeout),this._timeout[a][b][d].timeout=void 0)}}else window.clearTimeout(this._timeout[a][b])};this.removePlayer=function(b){for(var e in this._timeout[b])this._timeout[b].hasOwnProperty(e)&&(this.clearTimeout(b,e),a.richMedia.send({action:"stop",playerId:b,mediaLabel:e}));this._timeout[b]={}};this.removeAll=function(){for(var a in this._timeout)this._timeout.hasOwnProperty(a)&&this.removePlayer(a);this._timeout={}}},k=new function(){this._media=
function(){this.m9=this.m6=this.m5=this.m1=this.rfsh=this.buf=this.a=this.p=this.clnk=this.s2=this.plyr=this.type=""};this._mediaAll={};this.setMediaProperty=function(a,b,d,f){this._mediaAll[a]=this._mediaAll[a]||{};this._mediaAll[a][b]=this._mediaAll[a][b]||new this._media;this._mediaAll[a][b][d]=f};this.getMediaProperty=function(a,b,d){return this._mediaAll[a]&&this._mediaAll[a][b]?this._mediaAll[a][b][d]:""};this.removePlayer=function(a){this._mediaAll[a]={}};this.removeAll=function(){this._mediaAll=
{}}},f=function(b,e,d){var f=b[d]||"";a.exec("Utils","manageChapters",[b,e,3],function(a){f=a+f});return f},l=function(a,b,d,f){"boolean"===typeof a[b]&&a[b]&&(d=f);return d},h=function(a){var b=0;/^(\-|\+)?([0-9]+)$/.test(a)&&(b=Number(a));return b},g=function(a,b){var d=parseInt(a,10);return d?Math.max(d,b):0};a.richMedia={};a.richMedia.add=this.add=function(a){a=a||{};var b=h(a.playerId),d=f(a,"mediaTheme","mediaLabel"),g=l(a,"isBuffering","0","1"),q=l(a,"isEmbedded","int","ext");k.setMediaProperty(b,
d,"plyr",b);k.setMediaProperty(b,d,"type",a.mediaType||"");k.setMediaProperty(b,d,"s2",a.mediaLevel2||"");k.setMediaProperty(b,d,"p",d);k.setMediaProperty(b,d,"clnk",a.previousMedia||"");k.setMediaProperty(b,d,"a",a.action||"");k.setMediaProperty(b,d,"buf",g);k.setMediaProperty(b,d,"rfsh",a.refreshDuration||"");k.setMediaProperty(b,d,"m1",a.duration||"");k.setMediaProperty(b,d,"m5",q);k.setMediaProperty(b,d,"m6",a.broadcastMode||"");k.setMediaProperty(b,d,"m9",a.webdomain||"")};a.richMedia.remove=
this.remove=function(a){b.removePlayer(a);k.removePlayer(a)};a.richMedia.removeAll=this.removeAll=function(){b.removeAll();k.removeAll()};a.richMedia.send=this.send=function(c){c=c||{};var e=h(c.playerId),d=f(c,"mediaTheme","mediaLabel"),n={},q=l(c,"isBuffering","0","1");n.type=k.getMediaProperty(e,d,"type");n.plyr=e;n.p=d;n.a=c.action||"";n.s2=k.getMediaProperty(e,d,"s2");n.m1=k.getMediaProperty(e,d,"m1");n.m5=k.getMediaProperty(e,d,"m5");n.m6=k.getMediaProperty(e,d,"m6");if("play"===n.a||"info"===
n.a)n.buf=q,c=a.getContext("page")||{},n.prich=f(c,"chapter","name"),n.s2rich=c.level2||"",n.clnk=k.getMediaProperty(e,d,"clnk"),n.m9=encodeURIComponent(k.getMediaProperty(e,d,"m9"));a.sendHit(n,[["hitType",["richmedia"]]]);"pause"!==n.a&&"stop"!==n.a||b.clearTimeout(e,d);if("play"===n.a||"refresh"===n.a)n=k.getMediaProperty(e,d,"rfsh"),"object"===typeof n?b.setTimeoutObject(e,d,n):(n=g(n,5),0!==n&&b.setTimeout(e,d,n))}};window.ATInternet.Tracker.addPlugin("RichMedia");
}).call(window);;(function(){var dfltPluginCfg={"clicksAutoManagementEnabled":true,"clicksAutoManagementTimeout":500,"info":false};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.TechClicks=function(a){var b,k;a.configPlugin("TechClicks",dfltPluginCfg||{},function(a){b=a.clicksAutoManagementEnabled;k=a.clicksAutoManagementTimeout});this.deactivateAutoManagement=function(){b=!1};var f=function(a){switch(a.target){case "_top":window.top.location.href=a.url;break;case "_parent":window.parent.location.href=a.url;break;default:window.location.href=a.url}},l=function(a){var b=a.timeout;a.mailto?setTimeout(function(){window.location.href=a.mailto},
b):a.form?setTimeout(function(){a.form.submit()},b):a.url&&setTimeout(function(){f({url:a.url,target:a.target})},b)},h=function(b){for(var c,e="_self",g=b.timeoutonly;b;){if(b.href&&0===b.href.indexOf("http")){c=b.href.split('"').join('\\"');e=b.target?b.target:e;break}b=b.parentNode}if(c){if(!g)a.onTrigger("Tracker:Hit:Sent:Ok",function(){f({url:c,target:e})});l({url:c,target:e,timeout:k})}},g=function(b){var c=b;for(b=c.timeoutonly;c&&"FORM"!==c.nodeName;)c=c.parentNode;if(c){if(!b)a.onTrigger("Tracker:Hit:Sent:Ok",
function(){c.submit()});l({form:c,timeout:k})}},c=function(b){var c=b;for(b=c.timeoutonly;c&&!(c.href&&0<=c.href.indexOf("mailto:"));)c=c.parentNode;if(c){if(!b)a.onTrigger("Tracker:Hit:Sent:Ok",function(){window.location.href=c.href});l({mailto:c.href,timeout:k})}},e=function(a){for(;a;){if(a.href){if(0<=a.href.indexOf("mailto:"))return"mailto";if(0===a.href.indexOf("http"))return"redirection"}else if("FORM"===a.nodeName)return"form";a=a.parentNode}return!1};this.manageClick=function(a,f){if(b&&
a){var l;a:{for(l=a;l;){if("function"===typeof l.getAttribute&&("_blank"===l.getAttribute("target")||"no"===l.getAttribute("data-atclickmanagement"))){l=!0;break a}l=l.parentNode}l=a;for(var k=window.location.href,r;l;){if((r=l.href)&&0<r.indexOf("#")&&k.substring(0,0<k.indexOf("#")?k.indexOf("#"):k.length)===r.substring(0,r.indexOf("#"))){l=!0;break a}l=l.parentNode}l=!1}k=e(a);if(!l&&k){switch(k){case "mailto":c(a);break;case "form":g(a);break;case "redirection":h(a);break;default:return!0}f&&!f.defaultPrevented&&
f.preventDefault();return!1}}return!0}};window.ATInternet.Tracker.addPlugin("TechClicks");
}).call(window);;(function(){var dfltPluginCfg={"info":false};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.Utils=function(a){var b=this,k={};b.getQueryStringValue=function(a,b){var f=window.ATInternet.Utils.hashcode(b).toString();if(!k[f]){k[f]={};var c=RegExp("[&#?]{1}([^&=#?]*)=([^&#]*)?","g"),e=c.exec(b);if(null!==e)for(;null!==e;)k[f][e[1]]=e[2],e=c.exec(b)}return k[f].hasOwnProperty(a)?k[f][a]:null};b.customObjectToString=function(a){return encodeURIComponent(window.ATInternet.Utils.jsonSerialize(a))};b.manageChapters=function(b,f,g){var c=a.getConfig("ignoreEmptyChapterValue"),
e="";if(b){g=parseInt(g,10);for(var d=1;d<g+1;d++)var n=b[f+d]||"",e=c?e+(n?n+"::":""):e+(b.hasOwnProperty(f+d)?n+"::":"")}return e};b.getDocumentLevel=function(){var b=a.getConfig("documentLevel");if(0>b.indexOf("."))return window[b]||document;b=b.split(".");return window[b[0]][b[1]]||document};b.getLocation=function(){return b.getDocumentLevel().location.href};a.dispatchIndex={};a.dispatchStack=[];a.dispatchEventFor={};var f=0;a.dispatchSubscribe=function(b){return a.dispatchIndex[b]?!1:(a.dispatchStack.push(b),
a.dispatchIndex[b]=!0)};a.dispatchSubscribed=function(b){return!0===a.dispatchIndex[b]};a.addSpecificDispatchEventFor=function(b){return a.dispatchEventFor[b]?!1:(a.dispatchEventFor[b]=!0,f++,!0)};a.processSpecificDispatchEventFor=function(b){a.dispatchEventFor[b]&&(a.dispatchEventFor[b]=!1,f--,0===f&&(a.dispatchEventFor={},a.emit("Tracker:Plugin:SpecificEvent:Exec:Complete",{lvl:"INFO"})))};a.dispatch=function(){var b=function(){for(;0<a.dispatchStack.length;){var b=a.dispatchStack.pop();a[b].onDispatch()}a.dispatchIndex=
{};a.delContext(void 0,"customObject")},h=function(){if(a.plugins.isExecWaitingLazyloading())a.onTrigger("Tracker:Plugin:Lazyload:Exec:Complete",function(){b()},!0);else b()};if(0===f)h();else a.onTrigger("Tracker:Plugin:SpecificEvent:Exec:Complete",function(){h()},!0)};a.dispatchRedirect=function(b){var f=!0;b&&b.elem&&(b.elem.timeoutonly=!0,a.plugins.exec("TechClicks","manageClick",[b.elem],function(a){f=a}));a.dispatch();return f}};window.ATInternet.Tracker.addPlugin("Utils");
}).call(window);
if(typeof window.ATInternet.onTrackerLoad==='function'){window.ATInternet.onTrackerLoad();}